branches:
  only:
    - master

platform: x86

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

build: false

before_test:
  - pip install -r test-requirements.txt

test_script:
  - nosetests --cover-inclusive --cover-erase --cover-package=ntfsutils --with-coverage
